name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Check out the repository

    - name: Log into Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build project with Gradle
      run: ./gradlew build  # Builds the project

    - name: Build Docker image
      run: docker build -t anoopri/my-app:${{ github.sha }} .  # Build Docker image using the commit SHA as tag

    - name: Push Docker image
      run: docker push anoopri/my-app:${{ github.sha }}  # Push Docker image to Docker Hub
