name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: log into Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build project
      run: ./gradlew build 
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Push the Docker image to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: anoopri/my-app
        registry: docker.io
      
    - name: Build and Push Docker Image
      run: docker push my-image-name:$(date +%s)
